/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'appointmentDate' : IDL.Text,
  'message' : IDL.Text,
  'patientName' : IDL.Text,
  'phone' : IDL.Text,
  'doctorName' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'mapLink' : IDL.Text,
  'whatsapp' : IDL.Text,
  'ambulance' : IDL.Text,
  'hospitalPhone' : IDL.Text,
  'opdTimings' : IDL.Text,
});
export const Doctor = IDL.Record({
  'name' : IDL.Text,
  'specialization' : IDL.Text,
  'qualification' : IDL.Text,
});
export const HospitalInfo = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Appointment],
      [],
    ),
  'getAppointmentById' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getHospitalInfo' : IDL.Func([], [HospitalInfo], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getWhyChooseUs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'appointmentDate' : IDL.Text,
    'message' : IDL.Text,
    'patientName' : IDL.Text,
    'phone' : IDL.Text,
    'doctorName' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'mapLink' : IDL.Text,
    'whatsapp' : IDL.Text,
    'ambulance' : IDL.Text,
    'hospitalPhone' : IDL.Text,
    'opdTimings' : IDL.Text,
  });
  const Doctor = IDL.Record({
    'name' : IDL.Text,
    'specialization' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const HospitalInfo = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
  });
  const Service = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Appointment],
        [],
      ),
    'getAppointmentById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Appointment)],
        ['query'],
      ),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getHospitalInfo' : IDL.Func([], [HospitalInfo], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getWhyChooseUs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };