/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : string,
  'appointmentDate' : string,
  'message' : string,
  'patientName' : string,
  'phone' : string,
  'doctorName' : string,
  'timeSlot' : string,
}
export interface ContactInfo {
  'mapLink' : string,
  'whatsapp' : string,
  'ambulance' : string,
  'hospitalPhone' : string,
  'opdTimings' : string,
}
export interface Doctor {
  'name' : string,
  'specialization' : string,
  'qualification' : string,
}
export interface HospitalInfo {
  'tagline' : string,
  'name' : string,
  'description' : string,
  'address' : string,
}
export interface Service { 'name' : string, 'description' : string }
export interface _SERVICE {
  'bookAppointment' : ActorMethod<
    [string, string, string, string, string, string],
    Appointment
  >,
  'getAppointmentById' : ActorMethod<[bigint], [] | [Appointment]>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getDoctors' : ActorMethod<[], Array<Doctor>>,
  'getHospitalInfo' : ActorMethod<[], HospitalInfo>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getWhyChooseUs' : ActorMethod<[], Array<string>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];